package com.app.controller;

import com.app.model.Note;
import com.app.repository.NoteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.app.model.date.Date;

import java.time.Instant;
import java.util.List;


@Controller    // This means that this class is a Controller
@RequestMapping(path = "/notes") // This means URL's start with /demo (after Application path)
public class NoteController {

    @Autowired
    // This means to get the bean called noteRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NoteRepository noteRepository;

    @RequestMapping(method = RequestMethod.POST)
    public @ResponseBody
    String addNewNote(@RequestParam String title
            , @RequestParam String content) {

        Note n = new Note();
        n.setTitle(title);
        n.setContent(content);
        n.setInitialDate(Date.getCurrentDate().toString());
        n.setLastModificationDate(Date.getCurrentDate().toString());
        noteRepository.save(n);
        return "Saved\n";
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Note> getAllNotes() {
        return noteRepository.findAll();
    }


}